package com.edmko.setup

const val GOAL_FIELD_TAG = "GOAL_FIELD_TAG"
const val TYPE_FIELD_TAG = "TYPE_FIELD_TAG"
const val PLAYERS_LIST_TAG = "PLAYERS_LIST_TAG"
const val SELECT_GAME_TYPE_DIALOG_TAG = "SELECT_GAME_TYPE_DIALOG_TAG"
const val EDIT_GOAL_DIALOG_TAG = "EDIT_GOAL_DIALOG_TAG"
const val SETTINGS_ICON_TAG = "SETTINGS_ICON_TAG"
