rootProject.name = "UnoCounter"
include(":app")
include(":domain")
include(":data")
include(":navigation")
include(":core")
include(":features:setup")
include(":features:endgame")
include(":features:game")
include(":features:players")
include(":core-ui")
