#!/bin/bash
echo "*********************************************************"
echo "Running git pre-commit hook "
echo "*********************************************************"

# run ktlint
./gradlew --continue ktlintCheck

status=$?

# return 1 if check fails
if [[ $status -ne 0 ]]; then
     exit 1
else
     exit 0
fi